LobbyController/urls.py
from django.conf.urls import url
from django.contrib.auth import login, logout

from . import views

app_name = 'lobbies'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^create_lobby/$', views.create_lobby, name='create_lobby'),
	url(r'^leave_lobby/$', views.leave_lobby, name='leave_lobby'),
	url(r'^kick_player/$', views.kick_player, name='kick_player'),

	url(r'^join_lobby/(?P<lobbyId>\d+)/$', views.join_lobby, name='join_lobby'),
	url(r'^(?P<lobbyId>\d+)/$', views.lobby, name='lobby'),
	url(r'^login/$', views.lobby, name='login'),
	url(r'^logout/$', views.logout_session, name='logout_session'),
]

queueme/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lobbies/', include('LobbyController.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
]

LobbyController/models.py
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
import datetime

# Create your models here.

class Player(models.Model):
	nickname = models.CharField(max_length=255)
	avatar = models.CharField(max_length=255)
	url = models.CharField(max_length=255, unique=True)
	user = models.ForeignKey(User)
	rating = models.FloatField()
	rank = models.IntegerField()
	rank_lastUpdated = models.DateTimeField()

	currentLobby = models.ForeignKey('Lobby', models.SET_NULL, blank=True, null=True)

	def __str__(self):
		return self.nickname + " : " + self.url


class Lobby(models.Model):
	startTime = models.DateTimeField('Date the lobby was started')
	lobbyTitle = models.CharField(max_length=100, null=True)
	lobbyLeader = models.ForeignKey(Player, null=True)
	seat1 = models.ForeignKey(Player, null=True, related_name='seat1_players') 
	seat2 = models.ForeignKey(Player, null=True, related_name='seat2_players')
	seat3 = models.ForeignKey(Player, null=True, related_name='seat3_players')
	seat4 = models.ForeignKey(Player, null=True, related_name='seat4_players')
	seat5 = models.ForeignKey(Player, null=True, related_name='seat5_players')

	def __str__(self):
		return str(self.id)
	
	def create_lobby(player, title):
		try:
			Lobby.objects.get(lobbyLeader=player).delete()
		except ObjectDoesNotExist:
			swallow=1
		lobby = Lobby(
			startTime=datetime.datetime.now(), 
			lobbyTitle=title, 
			lobbyLeader=player
		)
		lobby.save()
		player.currentLobby = lobby
		player.save()
		return Lobby.objects.latest('id')

LobbyController/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseForbidden
from django.template import loader

from .models import Lobby, Player
from django.core.urlresolvers import reverse
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.shortcuts import redirect

def get_player(user):
	return Player.objects.get(user=user)

def index(request):
	lobbies = Lobby.objects.all()
	template = loader.get_template('lobbies/index.html')
	context = {
		'lobbies' : lobbies
	}
	if request.user.is_authenticated():
		context['curr_player'] = get_player(request.user)
	return HttpResponse(template.render(context,request))

def logout_session(request):
	logout(request)
	return redirect(reverse('lobbies:index'))
	
@login_required
def kick_player(request):
	lobbyId = request.GET['lobbyId']
	kickedPlayerId = request.GET['playerId']
	lobby = Lobby.objects.get(id=lobbyId)
	kickedPlayer = Player.objects.get(id=kickedPlayerId)
	self = Player.objects.get(user=request.user)
	if lobby.lobbyLeader == self:
		if self != kickedPlayer and kickedPlayer.currentLobby == lobby:
			kickedPlayer.currentLobby = None
			kickedPlayer.save()
	else:
		return HttpResponseForbidden("You cannot kick that player in that lobby.")
	return redirect(request.META.get('HTTP_REFERER'))

@login_required
def create_lobby(request):
	lobbyId = Lobby.create_lobby(get_player(request.user), request.POST['title'])
	return HttpResponseRedirect(reverse('lobbies:lobby',args=[lobbyId]))

@login_required
def join_lobby(request, lobbyId):
	lobbies = Lobby.objects.filter(id=lobbyId)
	if lobbies:
		lobby = lobbies[0]
		player = get_player(request.user)
		currentLobby = player.currentLobby
		if currentLobby:
			if currentLobby == lobby:
				return redirect(reverse('lobbies:lobby',args=[lobbyId]))
			elif currentLobby.lobbyLeader == player:
				currentLobby.delete()
		player.currentLobby = lobby
		player.save()
		return redirect(reverse('lobbies:lobby',args=[lobbyId]))
	else:
		return Http404("Not found")

@login_required
def leave_lobby(request):
	player = get_player(request.user)
	if player.currentLobby and player.currentLobby.lobbyLeader == player:
		player.currentLobby.delete()
	player.currentLobby = None
	player.save()
	return redirect(reverse('lobbies:index'))
		
@login_required
def lobby(request, lobbyId):
	lobbyEntry = Lobby.objects.get(id=lobbyId)
	players = Player.objects.filter(currentLobby=lobbyId)
	template = loader.get_template('lobbies/lobby.html')
	context = {}
	context = {
		'lobby' : lobbyEntry,
		'players' : players
	}
	context['curr_player'] = Player.objects.get(user=request.user)
		
	return render(request, 'lobbies/lobby.html', context)

LobbyController/templates/lobbies/base.html
<html>
<head>
	<title>Lobby App</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'lobbies:index'  %}">Queue Me</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'lobbies:index' %}">Lobbie List</a>
				</li>
				{% if curr_player.currentLobby %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'lobbies:lobby' curr_player.currentLobby.id %}">Current Lobby</a>
				</li>
				{% endif %}
			</ul>
      <ul class="nav navbar-nav navbar-right">
				{% if curr_player %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
							<img src="{{ curr_player.avatar }}" style="width:25;height:25"%> {{ curr_player.nickname }}
							<span class="caret"></span>
					</a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'lobbies:leave_lobby' %}">Leave Current Lobby</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'lobbies:logout_session' %}">Logout</a></li>
          </ul>
        </li>
				{% else  %}
				<a href="/login/steam?next={{ request.path }}">
					<img src="https://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_landing.png">
				</a>
				{% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	<div>
	</div>
	<div>
	{% block content %}	
	{% endblock %}
	</div>
</body>
</html>

LobbyController/templates/lobbies/index.html
{% extends 'lobbies/base.html' %}

{% block content %}
	<p>
	{% if curr_player %}
	Create lobby :
	<form action='{% url 'lobbies:create_lobby' %}' method='post'>
		{% csrf_token  %}
		<input type='text' name='title'>
		<input type='submit' value='Submit'>
	</form>
	{% else %}
	Please login to create a lobby.
	{% endif %}
	</p>
{% if lobbies %}
	<script>
	jQuery(document).ready(function($) {
		var rows = $(".clickable-row")
		rows.click(function() {
				window.document.location = $(this).data("url");
		});
		rows.css('cursor','pointer')
	});
	</script>
	<h3 class="text">Lobbies</h3>
	<table class="table table-hover">
		<thead>
		<tr>
			<th>id</th><th>Start Time</th><th>Title</th><th>Leader</th><th></th>
		</tr>
		</thead>
		<tbody>
    {% for lobby in lobbies %}
		<tr class="clickable-row" data-url="{% url 'lobbies:lobby' lobby.id %}">
			<td>{{ lobby.id }}</td>
			<td>{{ lobby.startTime }}</td>
			<td>{{ lobby.lobbyTitle }}</td>
			<td>{{ lobby.lobbyLeader.nickname }}</td>
			<td></td>
		</tr>
		</a>
    {% endfor %}
		</tbody>
	</table>
{% else %}
    <p>No lobbies available.</p>
{% endif %}
{% endblock %}

LobbyController/templates/lobbies/lobby.html
{% extends 'lobbies/base.html' %}
{% block content %}
{% if lobby %}
  <script>
		var messageHandlers = {
			'players' : function(message){
				playerTable = $("#playersTable > tbody");
				playerTable.empty();
				for (let player of message["players"]){
					var row  = $("<tr></tr>");
					row.append($("<td></td>").append($("<img>").attr("src", player["avatar"])));
					row.append($("<td></td>").append(player["nickname"]));
					row.append($("<td></td>").append(player["rating"] + " / 5"));
					row.append($("<td></td>").append(player["rank"]));
					playerTable.append(row);
				}
			},
			'chat' : function(message){
				chatArea = $("#chatArea");
				console.log(chatArea.length)
				chatArea.append((chatArea.val().length ? "\n" : "") + message["user"] + " : " + message["text"]);
				if(chatArea.length){
					chatArea.scrollTop(chatArea[0].scrollHeight - chatArea.height());
				}
			},
			'notice' : function(message){
				window.alert(message['text']);
			}
		}

		var url = 'ws://'+window.location.host + '{% url 'lobbies:lobby' lobby.id  %}';
		var socket = null;
		function createSocket(url){
			socket = new WebSocket(url);
			socket.onopen = function open() {
				console.log('WebSockets connection created.');
			};
			if (socket.readyState == WebSocket.OPEN) {
				socket.onopen();
			}
			socket.onmessage = function (event){
				message = JSON.parse(event.data);
				if (message["type"] in messageHandlers){
					messageHandlers[message["type"]](message["payload"]);
				}
			}
			socket.onclose = function (event){
				if (!event.wasClean){
					createSocket(url);
				}
			}
		}
		createSocket(url);

		function sendChatMessage(){
			var inputBox = $('#messagebox');
			if (inputBox.val().length){
				var message = {
					type : "chat",
					payload : {
						text : $('#messagebox').val()
					}
				}
				socket.send(JSON.stringify(message));
				inputBox.val("");
			}
		}
		function joinLobby(lobbyId){
			var message = {
				type : "joinLobby",
				payload : {
					lobbyId : lobbyId
				}
			}
			socket.send(JSON.stringify(message))
		}
  </script>
	<ul>
	<h3>{{ lobby.lobbyTitle }}</h3>
	<button onclick="joinLobby({{ lobby.id }})">Join Lobby</button>
	<div style="display:flex">
		<div style="flex-grow:1">
			<table id="playersTable" class="table table-striped">
				<thead>
				<tr>
					<th></th>
					<th>Nickname</th>
					<th>Rating</th>
					<th>Rank</th>
				</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
		</div>
		<div style="width:40%">
			<textarea id="chatArea" readonly=1 cols=30 rows=20 style="resize:none"></textarea>
			<input id="messagebox" size=29 onkeydown="if (event.keyCode == 13) { sendChatMessage(); return false; }" width="100%"><br>
		</div>

	</div>
	</ul>
{% else %}
	<p>No lobby with that id.</p>
{% endif %}
{% endblock %}